import os

ADMIN_USER_ID = 'chin'
SECRET_KEY = os.urandom(24)
DEBUG = True
DB_USERNAME = 'root'
DB_PASSWORD = '741444015'
DB_HOST = '127.0.0.1'
DB_PORT = '3306'
DB_NAME = 'citylife'
DB_URI = 'mysql+pymysql://%s:%s@%s:%s/%s?charset=utf8' % (DB_USERNAME, DB_PASSWORD, DB_HOST, DB_PORT, DB_NAME)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_POOL_SIZE = 0
SQLALCHEMY_MAX_OVERFLOW = -1
SQLALCHEMY_COMMIT_ON_TEARDOWN=True
SQLALCHEMY_ECHO = False
BOOTSTRAP_SERVE_LOCAL = True
TEMPLATES_AUTO_RELOAD = True
#CKEDITOR_FILE_UPLOADER = 'article.ckupload'
UPLOAD_FOLDER = '/static/upload'
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])
MAX_CONTENT_LENGTH = 32 * 1024 * 1024